[package]
name = "parables-example"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "GPL-3.0"

[dependencies]
pretty_env_logger = "0.2"
# parables-testing = {git = "https://github.com/primablock/parables"}
parables-testing = {path = "../testing"}
