#!/bin/bash

set -e

if ! command -v mdbook > /dev/null 2>&1; then
    cargo install mdbook
fi

ROOT=$(dirname $(dirname $(realpath $0)))

repo="git@github.com:primablock/parables.git"
target=$ROOT/target
target_doc=$target/doc/
checkout_book=$target/primablock.github.io_parables/
checkout_doc=$checkout_book/doc/
book=$ROOT/book
target_book=$book/book

# build the book
mdbook build $book
cargo doc

if [[ ! -d $target_book ]]; then
    echo "Missing: $target_book"
    exit 1
fi

git_do() {
    git --git-dir=$checkout_book/.git --work-tree=$checkout_book "$@"
    return $?
}

if [[ ! -d $checkout_book ]]; then
    echo "Initializing: $checkout_book"
    mkdir -p $checkout_book
    git_do init
    git_do remote add origin $repo
fi

git_do fetch -a origin gh-pages
git_do reset --hard origin/gh-pages
git_do clean -fdx

rsync -rav $target_book/ $checkout_book/
rsync -rav $target_doc/ $checkout_doc/

git_do add -A
git_do commit -m "Release $(date)"
git_do push origin HEAD:gh-pages
